version: '3.8'

services:
  redis:
    image: redis:8.0.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sandboxnet

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - sandboxnet

volumes:
  redis_data:

networks:
  sandboxnet:
    driver: bridge
